### ISSUE TITLE
feat: Implement the chat feature

### ISSUE THREAD

**Issue by kaali001** [kaali001/varta#17]
### **Is your feature request related to a problem? Please describe.**
 Currently chat page does not have the chat via messaging feature.

###  **Describe the solution you'd like**
Implementation of chat feature to two connected devices via webrtc is required.

**Comment by AkshayGowda-repo** [comment]
/assign
I'm interested please assign me this issue..

**Comment by kaali001** [comment]
@AkshayGowda-repo  , Actually Here we are using websocket for sending SDP and making a peer to peer connection b/w user  via WebRTC, and so the chat feature must be also implemented through this. because WebRTC can transfer not only audio/video streams but also arbitrary data between peers via DataChannels.

**Comment by kaali001** [comment]
You can start working on it. while following the contributing guidelines.

**Comment by kaali001** [comment]
@AkshayGowda-repo, Any update ?

**Comment by kaali001** [comment]
@AkshayGowda-repo, Any update ?
