### ISSUE TITLE
feat:  Add a active user count on the top right on header

### ISSUE THREAD

**Issue by kaali001** [kaali001/varta#18]
**Is your feature request related to a problem? Please describe.**

Currently visitor can't be able to see how many user are active now on the platform, so that they can match easily, as number of active user directly reflects the possibility of getting a match quickly.

**Describe the solution you'd like**

It is important to show the current active user, so that they can switch their comfort language accordingly to get a match quickly.

**Comment by Er-luffy-D** [comment]
Can i work on this @kaali001

**Comment by kartik-212004** [comment]
i would like to take this issue..thanks

**Comment by kaali001** [comment]
@Er-luffy-D ,  You have to add this on the chat page  and add a sample header on the chat page and better if you make separate component for both header and count feature, so that further it can be easy to modify.

**Comment by kaali001** [comment]
@kartik-212004 , you can look out for another issue.

**Comment by Er-luffy-D** [comment]
> @Er-luffy-D ,  You have to add this on the chat page  and add a sample header on the chat page and better if you make separate component for both header and count feature, so that further it can be easy to modify. 

Ok got it, I will try to do as you said

**Comment by Er-luffy-D** [comment]
> @Er-luffy-D ,  You have to add this on the chat page  and add a sample header on the chat page and better if you make separate component for both header and count feature, so that further it can be easy to modify. 

Ok got it, I will try to do as you said

**Comment by Er-luffy-D** [comment]
hey @kaali001, is it looking good ? 
![Screenshot 2024-10-25 200137](https://github.com/user-attachments/assets/59141da0-fc9f-4b8f-aa7e-58638dc09288)
![Screenshot 2024-10-25 200156](https://github.com/user-attachments/assets/25aa9625-2211-4ae3-95f6-17725ff4fa93)

**Comment by kaali001** [comment]
@Er-luffy-D , it would be better if you add a sample nav on top and on right side you implement user count. I have already mentioned this above. Make a a seperate navbar and usercount component and use it in chat page and please ensure if the functionality work as expected by joining the chat on different browsers and multiple tab.

**Comment by Er-luffy-D** [comment]
> @Er-luffy-D , it would be better if you add a sample nav on top and on right side you implement user count. I have already mentioned this above. Make a a seperate navbar and usercount component and use it in chat page and please ensure if the functionality work as expected by joining the chat on different browsers and multiple tab.

Currently, the user count functionality will work on any other tab until the Room component is used, as I’m setting its value from there. Is this alright, or should I create a GET request in index.js to fetch the user count?

**Comment by kaali001** [comment]
you, have set user count value from `server/managers/UserManager.js` and send this to a get request from the `User-count ` component in client and use this component in a navbar then implement this nav to the chat page. because then after we can use this where ever it required. And for checking the functionality you can open chat page in multiple tabs/browser and join the chat in all of them and ensure it works.

**Comment by Er-luffy-D** [comment]
> you, have to set user count value from `server/managers/UserManager.js` and send this to a get request from the `User-count ` component in client and use this component in a navbar then implement this nav to the chat page. because then after we can use this where ever it required. And for checking the functionality you can open chat page in multiple tabs/browser and join the chat in all of them and ensure it works. 

Thanks, @kaali001, for the guidance. I'll try to follow it as you've suggested.

**Comment by Er-luffy-D** [comment]
hey @kaali001 can i use material tailwind for sample nav ..., and i have completed the user count component just giving few touches to ui..

**Comment by kaali001** [comment]
No need to use any extra library, you just need a 2 rem height div with border at bottom.

**Comment by Er-luffy-D** [comment]
> No need to use any extra library, you just need a 2 rem height div with border at bottom. 
> 
> 

Ok thanks for confirming..

**Comment by Er-luffy-D** [comment]
hey @kaali001 is this alright ? 
![Screenshot 2024-10-29 155840](https://github.com/user-attachments/assets/6acfac38-c55a-4017-90ab-894609b73dfc)
![Screenshot 2024-10-29 160026](https://github.com/user-attachments/assets/0e68202d-c3d2-4d2c-a1e1-749265777fb0)
![Screenshot 2024-10-29 160052](https://github.com/user-attachments/assets/6c9e6aab-88fd-4942-a173-f3bab97e1159)

**Comment by kaali001** [comment]
Hey @Er-luffy-D ,  It looks good, Just make sure to check user count functionality by joining from two different browsers, And notice the user count  working. After This good to make PR, further if  any issue found during review I will let you know.
