### ISSUE TITLE
Feature Request: Custom Popover for Camera and Microphone Access

### ISSUE THREAD

**Issue by Suman-Jyoti-Phukan** [kaali001/varta#21]
**Is your feature request related to a problem? Please describe.**

To enhance user experience and ensure privacy transparency, I would like to implement a custom popover that explicitly asks for user permission to access the camera and microphone. The popover should provide clear context as to why the app needs these permissions, giving users full control over their privacy settings before initiating any media capture.

**Describe the solution you'd like**

A clean, easy-to-understand popover that prompts users to grant access to their camera and microphone. The popover will have clear messaging, either camera or audio access is grannted or denied, providing users control over their privacy.

**Describe alternatives you've considered**

Using the default browser permission request alone could work, but it lacks the customization and contextual information that helps users understand why access is being requested. (Current implementation)

** I have already tested out the component , and you can assign it to me under the hacktoberfest tag
** I have a attached a prototype of the component for better understanding

![Screenshot (1251)](https://github.com/user-attachments/assets/9e23c687-b816-4686-baea-d887de57561a)

**Comment by Suman-Jyoti-Phukan** [comment]
Thank you for the clarification. I’d be happy to take this on under Hacktoberfest. I’ll begin working on it, and once I push the PR, you can review it. Looking forward to your feedback.

Thanks again!

**Comment by kaali001** [comment]
You can start working on this feature while following the contribution guidelines.
