### ISSUE TITLE
Updating UI of chatpage

### ISSUE THREAD

**Issue by Vinit710** [kaali001/varta#3]
The current ui of chatpage looks simple and wastes so much space of the screen. 
![Screenshot 2024-10-13 181813](https://github.com/user-attachments/assets/ba4fa490-bd5e-4495-8360-d09218c4ae5f)

So i propose to making the UI better with have chat section on right side, so it looks good.

I am contributing under hacktober fest.

**Comment by kaali001** [comment]
@Vinit710   consider this while solving this issue,

Currently the self video renders in a 100 by 100 px window on left down side of other user video box, which must be corrected 
and both the video box should be equal. and the chat section on right side is correct but need some improvement. see below references and make changes accordingly , All buttons isn't necessary on video box but Leave room button should be added , And feel free to ask if you have any doubts or facing any error :   

![Main3](https://github.com/user-attachments/assets/0246cede-d5f7-4af2-8ff4-1953451aad5a)
