### ISSUE TITLE
Feature/ Enhancing the UI for the landing page.

### ISSUE THREAD

**Issue by imadityayadav** [kaali001/varta#5]
Enhancing the UI for the landing page making it look more appealing.
Please assign me this issue , i am mern stack developer with 2 years of experiance

**Comment by kaali001** [comment]
Please consider below color pallets and fonts for developing the Landing page interface - >
color pallet -  #d53b84,#fa546b, #c14020, #f1633d
Fonts -   Cinzel, Quattrocento, Ultine Extended Demi

And this page must contain a header containing Logo on left side , and on then Hero section may contain tag line with a Chat Now button on below side , It may contain some hero image which align with purpose. 
and feel free to use your creativity, and let me know if you encounter any issue or need any assistance.

**Comment by Anurag-singh-thakur** [comment]
Can you please assign it to me ... I am a UI designer followed by the developer skills

**Comment by kaali001** [comment]
Hey @Anurag-singh-thakur , can you express your thought on how you want to contribute ? And be specific.

**Comment by Anurag-singh-thakur** [comment]
> Hey @Anurag-singh-thakur , can you express your thought on how you want to contribute ? And be specific.

@kaali001 I am providing you my one of the project of mern stack if you like the ui then only assign to me ...i make sure that you will definitely love you landing page ui . here is my link (https://voting-app-frontend-67ba.onrender.com/)

**Comment by kaali001** [comment]
@Anurag-singh-thakur , You can discuss your approach with @imadityayadav and collaborate on this if both agree.

**Comment by kaali001** [comment]
@imadityayadav  any update ?

**Comment by Anurag-singh-thakur** [comment]
> @imadityayadav any update ?

Can I go ahead as he is not responding

**Comment by Anurag-singh-thakur** [comment]
> @imadityayadav any update ?

**Comment by Anurag-singh-thakur** [comment]
@kaali001 ... I will improve the ui of landing page for a good looking web application . For your reference here is an application that is built by me specially UI ( https://voting-app-65gn.onrender.com/) .. Please assign it to me

**Comment by kaali001** [comment]
@Anurag-singh-thakur I have already told you to collab with @imadityayadav, but it seems it didn't happen in a direction.
 go ahead now, And consider the above mentioned color palate and fonts while developing, below is a sample figma UI for landing page to start with, And also add all the necessary content and components that are required. And please discuss if you got a single issue or  required something, discussion section and discord is always there.

use logo present in public folder which fits well.

sample UI -  
![image](https://github.com/user-attachments/assets/5932a36e-8907-49e0-a6d7-c858b0c70964)

**Comment by Anurag-singh-thakur** [comment]
@kaali001  i want to ask the last thing ...do i need to clone this page exact that sample UI for landing page

**Comment by kaali001** [comment]
Keep  component on the page and header as it is because it's the main thing which user would interact most. And  let me know your idea for the interface .

**Comment by Anurag-singh-thakur** [comment]
> Keep component on the page and header as it is because it's the main thing which user would interact most. And let me know your idea for the interface .

will try my best ...will respond soon  thanks for assigning

**Comment by kaali001** [comment]
Hi @Anurag-singh-thakur,  Any update ?
